# Generated by Django 4.2.5 on 2023-10-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wav_license', models.IntegerField(default=30, verbose_name='Wav License $')),
                ('unlimited_license', models.IntegerField(default=100, verbose_name='Unlimited License $')),
                ('exclusive_license', models.IntegerField(default=300, verbose_name='Exclusive License $')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
    ]
