# Generated by Django 4.2.5 on 2023-10-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0002_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=32, unique=True, verbose_name='New mood')),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
            },
        ),
    ]
