# Generated by Django 4.2.5 on 2023-10-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0003_moods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=64, unique=True, verbose_name='Track Name')),
                ('cover_art', models.ImageField(upload_to='uploads/', verbose_name='Cover Art')),
                ('bpm', models.IntegerField(default=90, verbose_name='BPM')),
                ('key', models.CharField(max_length=16, verbose_name='Key')),
                ('duration', models.CharField(max_length=16, verbose_name='Duration')),
                ('mp3', models.FileField(upload_to='uploads/', verbose_name='Mp3 File')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm_site.moods')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
