# Generated by Django 4.2.5 on 2023-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0004_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='type_beat',
            field=models.CharField(default='Unique', max_length=32, verbose_name='Type Beat'),
        ),
    ]
