# Generated by Django 4.2.5 on 2023-12-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0006_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/store', verbose_name='HREF'),
        ),
    ]
