# Generated by Django 4.2.5 on 2024-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0008_tags_tracks_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Track priority'),
        ),
    ]
