# Generated by Django 4.2.5 on 2024-04-04 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0010_tracks_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm_site.tracks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchased Track',
                'verbose_name_plural': 'Purchased Tracks',
            },
        ),
    ]
