# Generated by Django 4.2.5 on 2024-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0012_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='unl_and_exc_link',
            field=models.URLField(blank=True, verbose_name='Link to unlimited and exclusive license files'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='waw_link',
            field=models.URLField(blank=True, verbose_name='Link to wav license files'),
        ),
    ]
