# Generated by Django 4.2.5 on 2024-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cm_site', '0018_alter_errorreport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedtrack',
            name='track_license',
            field=models.CharField(blank=True, choices=[('wav', 'Wav license'), ('unlimited', 'Unlimited license'), ('exclusive', 'Exclusive license')], max_length=20, null=True),
        ),
    ]
